# Translations template for designate.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the designate project.
#
# Translators:
# Corina Roe, 2014
msgid ""
msgstr ""
"Project-Id-Version: Designate\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-12 06:10+0000\n"
"PO-Revision-Date: 2014-11-11 17:54+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/designate/"
"language/fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: designate/api/middleware.py:267
msgid "Missing context in request, please check."
msgstr "Contexte manquant dans la requête. Veuillez vérifier."

#: designate/backend/impl_ipa/__init__.py:398
msgid ""
"Error: could not authenticate to IPA - please check for correct keytab file"
msgstr ""
"Erreur : impossible d'authentifier dans IPA - veuillez vérifier que vous "
"avez le fichier keytab qui convient"

#: designate/backend/impl_ipa/auth.py:55 designate/backend/impl_ipa/auth.py:60
#, python-format
msgid "caught kerberos exception %r"
msgstr "exception kerberos interceptée %r"

#: designate/manage/tlds.py:138
#, python-format
msgid "Number of errors: %d"
msgstr "Nombre d'erreurs : %d"

#: designate/manage/tlds.py:141
#, python-format
msgid ""
"Error Lines:\n"
"%s"
msgstr ""
"Lignes d'erreurs :\n"
"%s"

#: designate/mdns/handler.py:111
#, python-format
msgid "got exception while handling axfr request. Question is %(qr)s"
msgstr ""
"exception apparue lors du traitement des requêtes axfr La question est %(qr)s"

#: designate/mdns/service.py:92
#, python-format
msgid "Failed to deserialize packet from %(host)s:%(port)d"
msgstr "N'a pas pu dé-sérialiser le paquet de %(host)s:%(port)d"

#: designate/mdns/service.py:178
#, python-format
msgid "Unhandled exception while processing request from %(host)s:%(port)d"
msgstr ""
"Exception non prise en charge lors du traitement d'une requête en provenance "
"de  %(host)s:%(port)d"

#: designate/network_api/neutron.py:126
#, python-format
msgid "Failed calling Neutron %(region)s - %(endpoint)s"
msgstr "Échec de l'appel Neutron %(region)s - %(endpoint)s"

#: designate/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "en appel en boucle à durée fixe"

#: designate/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "en appel en boucle dynamique"

#: designate/openstack/common/policy.py:535
#: designate/openstack/common/policy.py:815
#, python-format
msgid "Failed to understand rule %s"
msgstr "N'a pas compris la règle %s"

#: designate/openstack/common/policy.py:545
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Aucun gestionnaire pour ce type de correspondance %s"

#: designate/openstack/common/service.py:269
msgid "Unhandled exception"
msgstr "Exception non prise en charge"
