# Translations template for designate.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the designate project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: designate 1.0.0.0b4.dev28\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-17 06:12+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: designate/policy.py:100
#, python-format
msgid "Policy check succeeded for rule '%(rule)s' on target %(target)s"
msgstr ""

#: designate/policy.py:104
#, python-format
msgid "Policy check failed for rule '%(rule)s' on target %(target)s"
msgstr ""

#: designate/service.py:91
#, python-format
msgid "Starting %(name)s service (version: %(version)s)"
msgstr ""

#: designate/service.py:96
#, python-format
msgid "Stopping %(name)s service"
msgstr ""

#: designate/service.py:207
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: designate/service.py:397
msgid "serve() can only be called once"
msgstr ""

#: designate/utils.py:444 designate/sqlalchemy/utils.py:112
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:32
msgid "An unknown exception occurred."
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:53
msgid "The service is unavailable"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:68
#, python-format
msgid "Infoblox backend is misconfigured: '%(option)s' must be defined."
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:73
#, python-format
msgid "Cannot search '%(objtype)s' object(s): %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:78
#, python-format
msgid "Cannot create '%(objtype)s' object(s): %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:83
#, python-format
msgid "Cannot delete object with ref %(ref)s: %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:88
#, python-format
msgid "Cannot update object with ref %(ref)s: %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:93
#, python-format
msgid ""
"Error occured during function's '%(func_name)s' call: ref %(ref)s: "
"%(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:98
msgid "No Infoblox Member is available."
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:102
#, python-format
msgid "Infoblox object cannot be parsed from dict: %(data)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:92
#, python-format
msgid "Issue happens during views creating: %s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:137
#, python-format
msgid "Infoblox %(obj_type)s already exists: %(ib_object)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:145
#, python-format
msgid "Infoblox %(obj_type)s was created: %(ib_object)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:164
#, python-format
msgid ""
"Infoblox %(obj_type)s will not be updated because it cannot be found: "
"%(payload)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:181
#, python-format
msgid "Infoblox object was updated: %s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:185
#, python-format
msgid ""
"Infoblox %(obj_type)s will not be deleted because it cannot be found: "
"%(payload)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:198
#, python-format
msgid "Infoblox object was deleted: %s"
msgstr ""

#: designate/cmd/manage.py:114
#, python-format
msgid "Could not read %s. Re-running with sudo"
msgstr ""

#: designate/cmd/manage.py:118
msgid "sudo failed, continuing as if nothing happened"
msgstr ""

#: designate/cmd/manage.py:120
msgid "Please re-run designate-manage as root."
msgstr ""

#: designate/manage/akamai.py:48
#, python-format
msgid "Failed to find target with ID %s"
msgstr ""

#: designate/manage/akamai.py:51
#, python-format
msgid "Found multiple targets with ID %s"
msgstr ""

#: designate/objects/base.py:550
#, python-format
msgid "<%(type)s count:'%(count)s' object:'%(list_type)s'>"
msgstr ""

