# Translations template for designate.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the designate project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: designate 2015.1.dev181\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-19 06:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: designate/dnsutils.py:104
#, python-format
msgid "Unknown TSIG key from %(host)s:%(port)d"
msgstr ""

#: designate/dnsutils.py:111
#, python-format
msgid "Invalid TSIG signature from %(host)s:%(port)d"
msgstr ""

#: designate/dnsutils.py:118
#, python-format
msgid "Failed to deserialize packet from %(host)s:%(port)d"
msgstr ""

#: designate/dnsutils.py:301
#, python-format
msgid "AXFR timed out for %(name)s from %(host)s"
msgstr ""

#: designate/dnsutils.py:305
#, python-format
msgid "Domain %(name)s is not present on %(host)s.Trying next server."
msgstr ""

#: designate/dnsutils.py:309
#, python-format
msgid "Connection error when doing AXFR for %(name)s from %(host)s"
msgstr ""

#: designate/dnsutils.py:313
#, python-format
msgid "Problem doing AXFR %(name)s from %(host)s. Trying next server."
msgstr ""

#: designate/dnsutils.py:320
#, python-format
msgid "XFR failed for %(name)s. No servers in %(servers)s was reached."
msgstr ""

#: designate/service.py:339
#, python-format
msgid "Unhandled exception while processing request from %(host)s:%(port)d"
msgstr ""

#: designate/api/middleware.py:267
msgid "Missing context in request, please check."
msgstr ""

#: designate/backend/impl_ipa/__init__.py:400
msgid ""
"Error: could not authenticate to IPA - please check for correct keytab "
"file"
msgstr ""

#: designate/backend/impl_ipa/auth.py:55 designate/backend/impl_ipa/auth.py:60
#, python-format
msgid "caught kerberos exception %r"
msgstr ""

#: designate/manage/tlds.py:138
#, python-format
msgid "Number of errors: %d"
msgstr ""

#: designate/manage/tlds.py:141
#, python-format
msgid ""
"Error Lines:\n"
"%s"
msgstr ""

#: designate/network_api/neutron.py:126
#, python-format
msgid "Failed calling Neutron %(region)s - %(endpoint)s"
msgstr ""

#: designate/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: designate/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: designate/openstack/common/service.py:268
msgid "Unhandled exception"
msgstr ""

#: designate/pool_manager/service.py:311
msgid ""
"An unhandled exception in periodic recovery occurred.  This should never "
"happen!"
msgstr ""

#: designate/pool_manager/service.py:341
msgid ""
"An unhandled exception in periodic sync occurred.  This should never "
"happen!"
msgstr ""

